### ISSUE TITLE
Failing test localgov_microsites_group\Functional\LoginTest::testLoginRedirect

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_microsites_group#503] opened 2024-10-01 10:55 UTC
Originally seen on https://github.com/localgovdrupal/localgov_microsites_group/pull/497 

but I think it is unrelated to that pull request.

https://github.com/localgovdrupal/localgov_microsites_group/actions/runs/10921854523/job/30315030608?pr=497

> 1) Drupal\Tests\localgov_microsites_group\Functional\LoginTest::testLoginRedirect
> Behat\Mink\Exception\ExpectationException: Current page is "/user/2", but "/admin" expected.
> 
> /var/www/html/web/core/tests/Drupal/Tests/WebAssert.php:591
> /var/www/html/web/core/tests/Drupal/Tests/WebAssert.php:779
> /var/www/html/web/modules/contrib/localgov_microsites_group/tests/src/Functional/LoginTest.php:80
> /var/www/html/vendor/phpunit/phpunit/src/Framework/TestResult.php:729
> 

@ekes commented there https://github.com/localgovdrupal/localgov_microsites_group/pull/497#issuecomment-2370599522

**Comment by stephen-cox** [comment] 2024-10-04 14:15
This test fails for me when run locally on the 4.x branch so doesn't look related to the changes in PR #497

**Comment by stephen-cox** [comment] 2024-10-04 14:55
Unfortunately, I've been able to track the cause of this failure with the time I've had available today.

It doesn't look to caused by a change to this module. Looking at the failures in test in GitHub Actions it started within the last 2 months, but the failure remains when running locally using commits predating this.

The failure looks to be because the DomainNegotiator is not returning the active domain (https://git.drupalcode.org/project/domain/-/blob/2.0.x/domain/src/DomainNegotiator.php?ref_type=heads#L146), but the test still fails in the beta1 version of Domain 2.

**Comment by finnlewis** [comment] 2024-10-10 18:47
Thanks @stephen-cox !

@millnut @ekes any fresh opinions?

**Comment by millnut** [comment] 2024-10-10 19:12
Diffing the modules installed between the last successful 4.x workflow the drupal/domain_path was also updated.

```
Working workflow
drupal/core (10.3.2)
drupal/domain (2.0.0-beta1)
drupal/domain_path (1.3.0)

==================

Failing workflow
drupal/core (10.3.5)
drupal/domain (2.0.0-beta2)
drupal/domain_path (1.4.0)
```

**Comment by millnut** [comment] 2024-10-11 19:52
Interesting I've done some further debugging and it may be something to do with drupal core, rolling back to the last successful version I was able to get the following

```
drupal/core (10.3.2) = Test passes
drupal/core (10.3.3) = Test passes
drupal/core (10.3.4) = Test fails
drupal/core (10.3.5) = Test fails
```

**Comment by millnut** [comment] 2024-10-11 21:09
@finnlewis tests fixed in https://github.com/localgovdrupal/localgov_microsites_group/pull/508

**Closed as completed** 2024-10-22 11:11 UTC
